import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../contexts/AuthContext";
import { PersonalInfoProvider } from "../contexts/PersonalInfoContext";
import { EducationProvider } from "../contexts/EducationContext";
import { ExperienceProvider } from "../contexts/ExperienceContext";
import { SkillsProvider } from "../contexts/SkillsContext";
import { LanguagesProvider } from "../contexts/LanguagesContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <PersonalInfoProvider>
            <EducationProvider>
              <ExperienceProvider>
                <SkillsProvider>
                  <LanguagesProvider>
                    {children}
                  </LanguagesProvider>
                </SkillsProvider>
              </ExperienceProvider>
            </EducationProvider>
          </PersonalInfoProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
